[phases.setup]
nixPkgs = ["nodejs_18", "openssl"]

[phases.install]
cmds = ["npm install"]

[phases.build]
cmds = ["npm run build", "npx prisma generate"]

[start]
cmd = "npx prisma migrate deploy && npm run start"
